---
- name: Install awx
  hosts: "awx"

  become: yes
  become_method: sudo
  
  tasks:
    - name: apt-get update
      apt:
        update_cache: yes

    - name: install common packages for python application development
      apt: pkg={{item}} state=latest
      become: yes
      with_items:
        - python
        - python-dev
        - python-pip
        - python-psycopg2
        - python-virtualenv

    - name: install stuff that docker needs
      apt: pkg={{item}} state=latest
      become: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: install docker ppg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker apt repo
      apt_repository:    
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: apt-get update again
      apt:
        update_cache: yes

    - name: install docker-ce
      apt: pkg={{item}} state=latest
      become: yes
      with_items:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io

    - name: copy requirements.txt
      become: yes
      template: src=requirements.txt dest=/vagrant/requirements.txt

    - name: pip install docker and ansible
      pip: 
        requirements: /vagrant/requirements.txt

    - name: Download NVM bash script
      get_url:
        url: https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh
        dest: /vagrant/install.sh

    - name: run NVM install
      command: bash /vagrant/install.sh
      become: yes
      become_user: vagrant
    
    - name: remove nvm install script
      file:
        path: /vagrant/install.sh
        state: absent 
    
    - name: make nvm script executable
      file:
        path: /home/vagrant/.nvm/nvm.sh
        mode: "u+x"

    - name: install node with NVM
      shell: 'source /home/vagrant/.nvm/nvm.sh && nvm install node 10.15.3'
      args:
        executable: /bin/bash
        chdir: /home/vagrant/
      become: yes
    
    - name: install docker compose
      shell: curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      become: yes

    - name: make docker-compose stuff exe
      file:
        path: /usr/local/bin/docker-compose
        mode: "u+x"

    - name: clone AWX repo
      git:    
        repo: 'https://github.com/ansible/awx.git'
        dest: /vagrant/awx
        update: yes
